name: Gradle Build

on:
  push:
    branches:
      - main
      - dev
      - feature_subscription_service_ui
  pull_request:
    branches:
      - main
      - dev
      - feature_subscription_service_ui
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        
      - name: List APK directory contents
        run: ls -la app/build/outputs/apk/release/
