name: Gradle Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Create artifacts directory
        run: mkdir -p ${{ github.workspace }}/artifacts
        
      - name: Copy APK to artifacts directory
        run: cp app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/artifacts/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: ${{ github.workspace }}/artifacts/
